;8237.ASM,MOV:RAM FROM 3000H TO 5000H;BYTE-MOV
CODE SEGMENT
ASSUME CS:CODE
PCTL    EQU 0FF23H ;控制口
PA      EQU 0FF20H ;字位口
PB      EQU 0FF21H ;字形口
PC      EQU 0FF22H ;键入口
CLEARF	EQU	0FF8CH
CH0A	EQU 	0FF80h
CH1A      EQU	0FF82H
CH1C	EQU	0FF83H
MODE	EQU	0FF8BH
CMMD	EQU	0FF88H
MASKS	EQU	0FF8FH
REQ	EQU	0FF89H
STATUS	EQU	0FF88H
rst	equ	0FF8dh
LATCH	EQU	9000H
	ORG 	2860H		;FORM EPROM FILE (.COM),SET ORG=0100H
START:  JMP START0
BUF     DB ?,?,?,?,?,?
data1:  db 0c0h,0f9h,0a4h,0b0h,99h,92h,82h,0f8h,80h,90h,88h,83h,0c6h,0a1h
        db 86h,8eh,0ffh,0ch,89h,0deh,0c7h,8ch,0f3h,0bfh,8FH
START0:	MOV SI,3000H
	MOV DI,5000H
	MOV CX,1FFFH
	MOV AL,00
	MOV DX,LATCH
	OUT DX,AL
	NOP
	NOP
	mov dx,rst
	out dx,al
	MOV DX,CLEARF
	OUT DX,AL
	MOV AL,0FH	;MASK_CH_0-3
	MOV DX,MASKS
	OUT DX,AL
	NOP
	NOP
	MOV DX,CH0A	;L-SAD
	MOV AX,SI
	OUT DX,AL
	MOV AL,AH
	OUT DX,AL
	NOP
	NOP
	MOV DX,CH1A	;L-DAD
	MOV AX,DI
	OUT DX,AL
	MOV AL,AH
	OUT DX,AL
	NOP
	NOP
	MOV AX,CX	;COUNT
	MOV DX,CH1C
	OUT DX,AL
	MOV AL,AH
	OUT DX,AL
	MOV AL,48H	;P_MODE
	MOV DX,MODE
	OUT DX,AL
	MOV AL,45H
	OUT DX,AL
	MOV AL,01H	;ON-8237
	MOV DX,CMMD
	OUT DX,AL
L1:	MOV AL,0EH	;UNMASK_CH_0
	MOV DX,MASKS
	OUT DX,AL
	MOV AL,04H	;START_DMA_TRANSFER
	MOV DX,REQ
	OUT DX,AL
	MOV DX,STATUS
	NOP
	NOP
WAIT1:	IN AL,DX
	TEST AL,03H
	JZ WAIT1
;	CALL CMP1
;	JNZ ERR

	MOV DX,CH1C
	IN AL,DX
	MOV AH,AL
	IN AL,DX
	CMP AX,0FFFFH
	JNZ L1
	CALL BUF1
	MOV CX,0080H
L2:	PUSH CX
	CALL DISP
	POP CX
	LOOP L2
	CALL BUF2
L3:	CALL DISP
	JMP L3
;---------------------------------------------
CMP1:	MOV DX,CH0A
	CALL CMP10
	MOV SI,AX
	MOV DX,CH1A
	CALL CMP10
	MOV DI,AX
	MOV AX,[SI]
	CMP [DI],AX
	RET
CMP10:	IN AL,DX
	MOV BL,AL
	IN AL,DX
	MOV AH,AL
	MOV AL,BL
	DEC AX
	RET
ERR:	CALL BUF3
ERR0:	CALL DISP
	JMP ERR0
;---------------------------
DISP:   MOV AL,0FFH         ;00H
	MOV DX,PA
	OUT DX,AL
	MOV CL,0DFH     ;20H           ;显示子程序 ,5ms
	MOV BX,OFFSET BUF
DIS1:   MOV AL,[BX]
        MOV AH,00H
	PUSH BX
	MOV BX,OFFSET DATA1
        ADD BX,AX
        MOV AL,[BX]
	POP BX
	MOV DX,PB
	OUT DX,AL
	MOV AL,CL
	MOV DX,PA
	OUT DX,AL
	PUSH CX
DIS2:	MOV CX,00A0H
DELAY:  LOOP DELAY
        POP CX
	CMP CL,0FEH  ;01H
	JZ LX1
	INC BX
	ROR CL,1     ;SHR CL,1
	JMP DIS1
LX1:    MOV AL,0FFH
	MOV DX,PB
	OUT DX,AL
	RET
BUF1:   MOV BUF,08H
        MOV BUF+1,02H
        MOV BUF+2,03H
        MOV BUF+3,07H
        MOV BUF+4,17H
        MOV BUF+5,17H
        RET
;-------------------------------------------------------------
BUF2:   MOV BUF,09H
        MOV BUF+1,00H
        MOV BUF+2,00H
        MOV BUF+3,0DH
        MOV BUF+4,10H
        MOV BUF+5,10H
        RET
BUF3:   MOV BUF,08H
        MOV BUF+1,02H
        MOV BUF+2,03H
        MOV BUF+3,07H
        MOV BUF+4,18H
        MOV BUF+5,18H
        RET
CODE ENDS
END  START

