CODE SEGMENT            ;H8255-1.ASM
ASSUME CS:CODE
IOCONPT EQU 0FF2BH
IOBPT	EQU 0FF29H
IOAPT	EQU 0FF28H
	ORG 11B0H
START:	MOV AL,90H
	MOV DX,IOCONPT
	OUT DX,AL
	NOP
	NOP
	NOP
IOLED1: MOV DX,IOAPT
	IN AL,DX
	MOV DX,IOBPT
	OUT DX,AL
	MOV CX,0FFFFH
DELAY:	LOOP DELAY
	JMP IOLED1
CODE ENDS
END  START
