CODE SEGMENT            ;JDQ.ASM
ASSUME CS:CODE
IOCONPT EQU 0FF2BH
IOBPT	EQU 0FF29H
IOAPT	EQU 0FF28H
	ORG 1810H
START:	MOV AL,88H
	MOV DX,IOCONPT
	OUT DX,AL
	NOP
	NOP
	NOP
IOLED1: MOV DX,IOAPT
IODE2:	MOV AL,01H
	OUT DX,AL
	CALL DELAY
	MOV AL,00H
	OUT DX,AL
	CALL DELAY
	JMP IODE2
DELAY:	MOV CX,0FFFFH
DELY:	LOOP DELY
	RET
CODE ENDS
END  START
