	CODE SEGMENT    ;S5.ASM,CLR
	ASSUME CS:CODE
	ORG 2DC0H	;this is a program of clear "0"
START: 	MOV AL,00H	;CLEAR RAM:4000--4FFFH
	MOV BX,4000H
CON1:	MOV [BX],AL
	INC BX
	CMP BX,5000H
	JNE CON1
	JMP $
	CODE ENDS
	END  START
